import json
from pathlib import Path
from typing import Any

from jsonschema import validate


PROJECT_ROOT = Path(__file__).resolve().parents[2]

REQUEST_PATH = (
    PROJECT_ROOT
    / "examples"
    / "requests"
    / "create-line.json"
)

SCHEMA_PATH = (
    PROJECT_ROOT
    / "schemas"
    / "v0.1"
    / "command.schema.json"
)

OUTPUT_PATH = (
    PROJECT_ROOT
    / "backend"
    / "output"
    / "mock-response.json"
)

# For this mock, pretend the active AutoCAD drawing uses inches.
MOCK_DRAWING_UNITS = "inches"


def load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"Could not find file: {path}")

    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def convert_to_inches(value: float, units: str) -> float:
    conversion_factors = {
        "inches": 1.0,
        "feet": 12.0,
        "millimeters": 1.0 / 25.4,
        "meters": 39.3700787402,
        "drawing_units": 1.0,
    }

    if units not in conversion_factors:
        raise ValueError(f"Unsupported units: {units}")

    return value * conversion_factors[units]


def convert_point_to_drawing_units(
    point: dict[str, float],
    source_units: str,
) -> list[float]:
    return [
        convert_to_inches(point["x"], source_units),
        convert_to_inches(point["y"], source_units),
        convert_to_inches(point["z"], source_units),
    ]


def process_create_line(command: dict[str, Any]) -> dict[str, Any]:
    parameters = command["parameters"]
    units = command["units"]

    start = convert_point_to_drawing_units(
        parameters["start"],
        units,
    )

    end = convert_point_to_drawing_units(
        parameters["end"],
        units,
    )

    return {
        "schema_version": command["schema_version"],
        "command_id": command["command_id"],
        "status": "success",
        "message": "Mock line created successfully.",
        "affected_objects": [
            {
                "object_type": "LINE",
                "object_id": "MOCK-LINE-001",
                "action": "created",
            }
        ],
        "data": {
            "mock_mode": True,
            "drawing_units": MOCK_DRAWING_UNITS,
            "layer": parameters["layer"],
            "start_in_drawing_units": start,
            "end_in_drawing_units": end,
        },
        "undo_token": "mock-ai-action-001",
        "warnings": [
            "This response was generated by the mock backend. AutoCAD was not modified."
        ],
    }


def process_command(command: dict[str, Any]) -> dict[str, Any]:
    operation = command["operation"]

    if operation == "create_line":
        return process_create_line(command)

    raise ValueError(f"Unsupported operation: {operation}")


def main() -> None:
    command = load_json(REQUEST_PATH)
    schema = load_json(SCHEMA_PATH)

    # Reject the command if it does not match our schema.
    validate(instance=command, schema=schema)

    response = process_command(command)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    with OUTPUT_PATH.open("w", encoding="utf-8") as file:
        json.dump(response, file, indent=2)

    print("Mock backend completed successfully.")
    print(f"Operation: {command['operation']}")
    print(f"Command ID: {command['command_id']}")
    print(f"Response saved to: {OUTPUT_PATH}")


if __name__ == "__main__":
    main()